//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercadito_Chavez_Sanabria.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LU0JGQQ;Initial Catalog=Mercado_Chavez_Sanabria;Integrated Se" +
            "curity=True;TrustServerCertificate=True")]
        public string Mercado_Chavez_SanabriaConnectionString {
            get {
                return ((string)(this["Mercado_Chavez_SanabriaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-VSK9D5VK\\NC10FA;Initial Catalog=Mercado_Chavez_Sanabria;Integr" +
            "ated Security=True;TrustServerCertificate=True")]
        public string Mercado_Chavez_SanabriaConnectionString1 {
            get {
                return ((string)(this["Mercado_Chavez_SanabriaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-C50FLTL;Initial Catalog=Mercado_Chavez_Sanabria;Integrated Se" +
            "curity=True;TrustServerCertificate=True")]
        public string Mercado_Chavez_SanabriaConnectionStringesta {
            get {
                return ((string)(this["Mercado_Chavez_SanabriaConnectionStringesta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=Mercado_Chavez_Sanabria;Integrated Security" +
            "=True;TrustServerCertificate=True")]
        public string Mercado_Chavez_SanabriaConnection {
            get {
                return ((string)(this["Mercado_Chavez_SanabriaConnection"]));
            }
        }
    }
}
